version: "3.9"
services:
  front:
    build: ./frontend
    ports:
      - "3000:80"
      
  kdb:
    build: ./q
    volumes:
      - /mnt/ssd1:/tables
    ports:
      - "5010:5010"
      - "5011:5011"
      - "5012:5012"

  back:
    build: ./backend
    ports:
      - "8000:8000"
      - "6379:6379"
    depends_on:
      - kdb
  